project:
  type: website
  output-dir: docs

website:
  title: "a-nhmai.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css

editor: visual

