project:
  type: website
  output-dir: docs

website:
  title: "MaiPage"
  navbar:
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - Mini-Project1.qmd
     - Mini-Project2.qmd

format:
  html:
    theme:
      light: mint
      dark: solar
    css: styles.css

editor: visual

