---
project:
  type: website
  output-dir: docs
website:
  title: MaiPage
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Mini-Project1.qmd
        text: Mini Project 1
      - href: Mini-Project2.qmd
        text: Mini Project 2
format:
  html:
    theme:
      light: mint
      dark: solar
    css: styles.css
    
editor: visual

publish:
  server: shinyapps
  account: maipage