project:
  type: website

website:
  title: " "
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    right: Copyright 2026, Anh Mai

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full

editor: visual

